language: node_js
node_js:
  - 10
before_script:
  - npm install
  - npm run build:scss
script: npm run build:docs
deploy:
  local-dir: docs/_site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
