# Site settings
title: "Matrix"
description: "A minimal CSS grid framework. Based on CSS Grid Layout."
url: "https://glascode.github.io"
baseurl: "/matrix"
repository: "https://github.com/glascode/grid-system"

# Build settings
kramdown:
  input: GFM
