# Site settings
title: "Grid System"
description: "Yet another minimal CSS framework. Based on CSS Grid Layout."
baseurl: "/grid-system"

# Build settings
include: ["_pages"]  # include more files
kramdown:
  input: GFM
